[package]
name = "dsmr_save"
version = "0.1.0"
edition = "2024"

[dependencies]
dsmr5 = "0.4.0"
env_logger = "0.11"
log = "0.4"
serial2 = "0.2.33"
time = "0.3"
ureq = { version = "3.1.4", default-features = false, features = ["rustls"] }

